# Generated by Django 5.1.7 on 2025-03-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[('T', 'Text Type'), ('I', 'Image Type')], default='T', max_length=1),
        ),
    ]
