# Generated by Django 5.1.7 on 2025-04-30 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_challenge_challenge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.challenge'),
        ),
    ]
