# Generated by Django 5.1.7 on 2025-05-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_challenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='points',
            new_name='likes',
        ),
    ]
