# Generated by Django 5.1.6 on 2025-02-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_challenge_num_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ranking',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
