# Generated by Django 5.1.6 on 2025-02-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_challenge_ranking_post_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_vote',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_times',
            field=models.IntegerField(default=0),
        ),
    ]
