# Generated by Django 5.1.7 on 2025-03-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_current_vote_user_vote_closed_user_vote_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='detail_es',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
