# Generated by Django 5.1.7 on 2025-03-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
