# Generated by Django 5.1.6 on 2025-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_followed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='num_followers',
            field=models.IntegerField(default=0),
        ),
    ]
