# Generated by Django 5.1.6 on 2025-02-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_challenge_post_date_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='detail',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.challenge'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
