# Generated by Django 5.1.6 on 2025-02-07 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.challenge'),
        ),
    ]
