# Generated by Django 5.1.6 on 2025-02-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_post_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='num_posts',
            field=models.IntegerField(default=0),
        ),
    ]
